site_name: 宁波大学课程攻略共享计划
site_url: https://NBUComputerRepairClub.github.io/nbu-icicles/
site_description: 宁波大学课程攻略共享计划
repo_name: nbu-icicles
repo_url: https://github.com/NBUComputerRepairClub/nbu-icicles/
edit_uri: tree/main/docs

nav :
  - 主页: 
    - index.md
    - 贡献指南: contributing.md
    - 课程页面模板: template.md
  - 本科生课程: 
    - 概览: 本科生课程/index.md
    - 体育选课: 本科生课程/选课信息/physics.md
    - 毕业设计: 本科生课程/毕业设计/readme.md
    - 毕业实习: 本科生课程/毕业实习/readme.md    
    - 数值计算: 本科生课程/数值计算/readme.md
    - 随机过程: 本科生课程/随机过程/readme.md
  - CS专业课:
    - 概览: CS专业课/index.md
    - 大二上:
       - CS专业课/大二上/index.md
       - 概率论: CS专业课/大二上/概率论/index.md
       - 离散数学: CS专业课/大二上/离散数学/index.md
       - 数字电路: CS专业课/大二上/数字电路/index.md
       - Matlab与数值计算: CS专业课/大二上/Matlab与数值计算/index.md
    - 大三上:
       - CS专业课/大三上/index.md
       - 数据库: CS专业课/大三上/数据库/index.md
       - 汇编语言与接口技术: CS专业课/大三上/汇编语言与接口技术/index.md
       - 操作系统 : CS专业课/大三上/操作系统/index.md
       - 软件工程 : CS专业课/大三上/软件工程/index.md
       - 网络工程课程设计 : CS专业课/大三上/网络工程课程设计/index.md
       - 软硬件基础课程设计 : CS专业课/大三上/软硬件基础课程设计/index.md
       - 无线网络 : CS专业课/大三上/无线网络/index.md
       - 移动应用开发 : CS专业课/大三上/移动应用开发/index.md
       - Java高级应用 : CS专业课/大三上/Java高级应用/index.md
    - 大三下:
       - CS专业课/大三下/index.md
       - 编译原理 : CS专业课/大三下/编译原理/index.md
       - 嵌入式系统: CS专业课/大三下/嵌入式系统/index.md
       - 软件实习项目: CS专业课/大三下/软件实习项目/index.md
       - 算法设计与分析: CS专业课/大三下/算法设计与分析/index.md
       - 网络集成实习: CS专业课/大三下/网络集成实习/index.md
       - 信息安全技术: CS专业课/大三下/信息安全技术/index.md
       - IT项目管理: CS专业课/大三下/IT项目管理/index.md
    
  - EE专业课:
    - 概览: EE专业课/index.md
    - 智能控制导论: EE专业课/智能控制导论/index.md
    
  - 竞赛:
    - 简介/竞赛.md
    - 飞桨黑客马拉松: 竞赛/paddle.md
    - 电子设计竞赛: 竞赛/电子设计竞赛.md
    - 机器人竞赛: 竞赛/机器人竞赛.md

  - 升学:
    - 简介/升学.md

  - 工作:
    - 简介/工作.md

  - 百科:
    - 简介/百科.md

  
theme:
  name: 'material'
  language: 'zh'
  # logo: images/icon.png
  icon: # 图标
    logo: material/notebook-outline
    repo: fontawesome/brands/github
    edit: material/pencil
  custom_dir: overrides # 使用扩展主题
  features:
    - content.code.annotate #启用代码注释特性
    - content.action.edit #启用编辑按钮
    - navigation.tracking #启用导航跟踪
    - navigation.top #启用顶部导航特性
    - navigation.tabs #启用导航标签特性。
    - navigation.footer #启用页脚导航特性。
    - navigation.indexes #启用索引导航特性。
    - navigation.sections #启用章节导航特性。
  font:
    # text: Noto Serif SC
    code: JetBrains Mono
  palette:
    - scheme: default #配置颜色方案
plugins:
  - search
  - heti:
      extra_skipped_class:
        - arithmatex
  # 不使用ZJU-Turing的插件：
  # - turing_changelog
  # - turing_contributors
  # - turing_evaluations
  # - turing_outdate_warning  
        
extra_css: # 额外的 CSS 文件
  - https://fonts.googleapis.com/css?family=Noto+Serif+SC:300,300i,400,400i,700,700i&display=fallback
  - css/tasklist.css
  - css/card.css
  - css/custom.css

extra_javascript:  # 额外的 JavaScript 文件
  - js/katex.js


markdown_extensions:
  - toc:  # 目录扩展，为每个页面生成目录
      permalink: true  # 每个标题都有一个永久链接
      toc_depth: 4  # 目录的深度为 4
  - meta  # 元数据扩展
  - def_list  # 定义列表扩展
  - attr_list  # 属性列表扩展
  - md_in_html  # 在 HTML 中使用 Markdown 的扩展
  - sane_lists  # 更合理的列表扩展
  - admonition  # 警告框扩展
  - pymdownx.keys  # 表示键盘按键的扩展
  - pymdownx.mark  # 标记扩展
  - pymdownx.tilde  # 波浪线扩展
  - pymdownx.critic  # 批评扩展
  - pymdownx.details  # 详细信息扩展
  - pymdownx.snippets  # 代码片段扩展
  - pymdownx.magiclink  # 魔术链接扩展
  - pymdownx.superfences  # 超级围栏扩展
  - pymdownx.inlinehilite  # 内联高亮扩展
  - pymdownx.emoji:  # emoji 扩展
      emoji_index: !!python/name:materialx.emoji.twemoji  # emoji 的索引
      emoji_generator: !!python/name:materialx.emoji.to_svg  # emoji 的生成器
  - pymdownx.tabbed:  # 制表符扩展
      alternate_style: true  # 使用替代样式
  - pymdownx.tasklist:  # 任务列表扩展
      custom_checkbox: true  # 使用自定义的复选框
  - pymdownx.highlight:  # 代码高亮扩展
      anchor_linenums: true  # 每一行都有一个锚点
  - pymdownx.arithmatex:  # 数学公式扩展
      generic: true  # 使用通用模式
